Golang functionality for SA
fabric8-analytics/fabric8-analytics-utils pull request #65
Opened 2020-09-12 17:06 UTC by deepak1725

Golang functionality for SA

2020-09-14 06:55 UTC, prashbnair requested changes
@deepak1725 Can we split this into a factory, abstract class and concrete implementations for each ecosystem?

2020-09-14 07:19 UTC, deepak1725 commented
> @deepak1725 Can we split this into a factory, abstract class and concrete implementations for each ecosystem?

Probably we will take this as Refactor Job. Currently i just followed what Pattern is being followed earlier.

2020-09-14 08:26 UTC, yzainee requested changes

2020-09-14 08:26 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +                if '@' in prefix and suffix not in direct:
Take the example of tests/data/gograph.txt. "github.com/cosmos/cosmos-sdk" should not be added as a direct dependency as its the name of the module. i dont see any logic which is doing so.

2020-09-14 08:26 UTC, yzainee commented on tests/data/gograph.txt
> +github.com/cosmos/cosmos-sdk github.com/99designs/keyring@v1.1.5
This test data is wrong. There are 3 direct deps for the module cosmos-sdk, but there is no reference for any of those direct deps further in the file for any of its transitives. whereas some random other pkgs are being used for transitives.

2020-09-14 08:26 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +                    direct.append(suffix)
This is an incorrect logic. This whole if blocks needs to be refactored. The current logic is going to ignore all the actual direct dependencies and add several transitives as direct which is totally wrong.

2020-09-14 08:40 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        dependencies = dependencies[:dependencies.rfind('\n')]
So, we see the next line of this is `dependencies.split('\n')` which splits on '\n' and makes a List to iterate on.

The problem is when there is a Newline at the end of each text file, we have an empty list like `["abc", " " ]`.

This line is just to avoid that thing.

2020-09-14 09:15 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +        dependencies = dependencies[:dependencies.rfind('\n')]
Ok. Do we get such generated files? Is there a way it can be avoided during the file generation itself? If no, then this code is fine

2020-09-14 10:48 UTC, arajkumar requested changes

2020-09-14 10:48 UTC, arajkumar commented on f8a_utils/dependency_finder.py
> +                            dependencies, transitive, suffix, trans)
Looks like the implementation is doing a n^2 pass parsing. The given nature of problem could be solved with 2 pass parser.(with the help of map it would be log2 n pass parser).

2020-09-14 10:48 UTC, arajkumar commented on tests/test_depencency_finder.py
> +def test_scan_and_find_dependencies_golang():
Could you please add tests for following scenarios as well?
1. Empty gograph
2. Only direct

2020-09-14 10:48 UTC, arajkumar commented on f8a_utils/dependency_finder.py
> +                        "deps": transitive
IIRC, dependency_finder used to expose only [package, version, deps: [package, version]. What is the purpose of `from`, `given_version`, `is_semver` which seems to be added ultimately for golang? Sorry If I missed some discussion.

2020-09-14 10:48 UTC, arajkumar commented on f8a_utils/dependency_finder.py
> +        dependencies = dependencies[:dependencies.rfind('\n')]
@deepak1725 Can you add a test case to showcase this use case?

2020-09-14 11:08 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +                            dependencies, transitive, suffix, trans)
> Looks like the implementation is doing a n^2 pass parsing.

So are `get_maven_dependencies`

Thanks for your nice comments. We will be focusing on Functionality only for now.

2020-09-14 12:13 UTC, arajkumar commented on f8a_utils/dependency_finder.py
> +                            dependencies, transitive, suffix, trans)
@deepak1725 I didn't get your point. It is not necessary that all new code has to follow the existing one even if it is bad.

I have raised a similar concern for maven too when @dgpatelgit was doing some changes over there. https://github.com/fabric8-analytics/fabric8-analytics-utils/pull/56#pullrequestreview-452511996

2020-09-14 12:14 UTC, arajkumar commented on f8a_utils/dependency_finder.py
> +                            dependencies, transitive, suffix, trans)
I leave this upto @prashbnair . Thanks.

2020-09-14 12:53 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +                    direct.append(suffix)
Please check now.

2020-09-14 12:53 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +                if '@' in prefix and suffix not in direct:
Please check now.

2020-09-14 14:01 UTC, prashbnair requested changes

2020-09-14 14:08 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +                    transitive_list = DependencyFinder.get_go_transitives(dependencies, direct_dep)
@prashbnair I agree with both of you.. but We decided to have functionality checks only as of now in the interest of time. Design comments can be put on the backburner. So, I'm more inclined in putting this in TODO.

2020-09-14 14:09 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +    def get_golang_dependencies(ecosystem, manifests, show_transitive):
This is to match signatures with other ecosystem functions.

2020-09-14 14:23 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +            print("Manifest")
Ack!

2020-09-14 15:50 UTC, prashbnair commented on f8a_utils/dependency_finder.py
> +                    transitive_list = DependencyFinder.get_go_transitives(dependencies, direct_dep)
@deepak1725 Please create a refactor jira with all the items listed. I am hoping that all of this can be picked can be picked up in the upcoming sprint.

2020-09-15 04:50 UTC, deepak1725 commented on tests/data/gograph.txt
> +github.com/cosmos/cosmos-sdk github.com/99designs/keyring@v1.1.5
Ack!. Test Data Modified

2020-09-15 04:59 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +                    transitive_list = DependencyFinder.get_go_transitives(dependencies, direct_dep)
@prashbnair Here it is https://issues.redhat.com/browse/APPAI-1483

2020-09-15 05:00 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +            raise ValueError('Invalid Maven coordinates %s', deps_string)
Ack

2020-09-15 06:45 UTC, dgpatelgit reviewed
We are not considering '+incompatible' string in the version. Recent discussion on handling +incompatible has to be handled for golang. Backbone / graph db does not store this string along with version, We need handle them gracefully. Also when CA message is build for 'diagnostic message' and 'quick fix', we need to display this string. This is looks like missed.

2020-09-15 06:45 UTC, dgpatelgit commented on f8a_utils/dependency_finder.py
> +        a['is_semver'] = a['given_version'].count('-') == 0
I found during plugin development that '-' count == 0 cannot be consider has non-semversion, because v2.3.0-apha and v1.25.4-beta.3.4 are all valid sem versions. We need to re-look at this logic.

2020-09-15 06:45 UTC, dgpatelgit commented on f8a_utils/dependency_finder.py
> +        a['version'] = a['given_version'].replace('v', '').split('-')[0].split('+')[0]
Ideally I prefer to use some semver() python package to extract the version string and identify the version type.

2020-09-15 07:15 UTC, deepak1725 commented
> We are not considering '+incompatible' string in the version.

@dgpatelgit +incompatible is handled gracefully.

In response, we have `"given_version": "v1.1.5",` and `"version": "1.1.5"` ..
given version- is same as what user Supplied
version - is cleaned up version.

2020-09-15 07:16 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +            a['package'], a['given_version'] = deps_string.split('@')
https://github.com/fabric8-analytics/fabric8-analytics-utils/pull/65#issuecomment-692517072

2020-09-15 07:35 UTC, yzainee requested changes

2020-09-15 07:35 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +        a['is_semver'] = a['given_version'].count('-') == 0
This isnt correct. This will also ignore alpha beta gamma. you need to filter using a regex to check for commit hash

2020-09-15 07:35 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +                if show_transitive and (direct_dep not in direct_list):
This is still not correct. Taking the example of your gograph.txt, github.com/cosmos/cosmos-sdk is the name of the module and its not a direct dep. From line number 1 to 39, whatever comes after github.com/cosmos/cosmos-sdk is actually the direct dep. From there on, for each of this direct, you can find its corresponding transitives list.

2020-09-15 07:35 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +                if show_transitive and (direct_dep not in direct_list):
you can check similar logic in maven dependencies.txt There too we need to exclude the project name, pick the direct and then find their transitives.

2020-09-15 07:35 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +                    transitive_list = DependencyFinder.get_go_transitives(dependencies, direct_dep)
@prashbnair @arajkumar each direct can have multiple transitives, each of this transitive can have again its own list of transitives and this nesting can go on till the end. We get all these transitives and have it in a flat list of transitives under a direct. Not sure how you plan to have this refactored with lesser complexity. It also requires multiple recursive traversals

2020-09-15 14:21 UTC, arajkumar commented on f8a_utils/dependency_finder.py
> +                    transitive_list = DependencyFinder.get_go_transitives(dependencies, direct_dep)
@yzainee The ask was to avoid repeated parsing of input for each & every transitive. The idea is to parse the input and load it into a data structure on the 1st pass. Do the 2nd pass iterate over the data structure to convert it to the required format.

2020-09-15 18:12 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +                if show_transitive and (direct_dep not in direct_list):
ack!

2020-09-15 18:13 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        a['is_semver'] = a['given_version'].count('-') == 0
Leveraging Package `semver`

2020-09-15 18:32 UTC, deepak1725 commented
[test]

2020-09-16 05:44 UTC, dgpatelgit commented on f8a_utils/dependency_finder.py
> +    def clean_version(version):
Rename this function to ecosystem specific as we have other functions like clean_go_version().

2020-09-16 05:44 UTC, dgpatelgit commented on f8a_utils/dependency_finder.py
> +        return is_semver, version
Unit test to verify this function is very important, can we have test case with only semver, semver+incompatible, semver-alpha, semver-beta.3.4 etc. This will ensure all the versions that we have thought of in gograph file and are working as expected.

2020-09-16 05:44 UTC, dgpatelgit commented on f8a_utils/dependency_finder.py
> +    def parse_go_string(deps_string):
Add unit test case to ensure parsing of gograph string into version information.

2020-09-16 05:54 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        return is_semver, version
@dgpatelgit 
Procedural Test is Written.. which covers every newly written function. I don't feel there is a need to have the Unit Test individually again.

2020-09-16 05:55 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +    def parse_go_string(deps_string):
https://github.com/fabric8-analytics/fabric8-analytics-utils/pull/65#discussion_r489180108

2020-09-16 05:58 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +    def clean_version(version):
@dgpatelgit There is nothing specific to golang in this method. it can be used by any other ecosystem too.

2020-09-16 06:23 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        return is_semver, version
Added Unit Tests also. Thanks

2020-09-16 06:24 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +    def parse_go_string(deps_string):
Added Unit Tests also. Thanks

2020-09-16 07:24 UTC, deepak1725 commented on tests/test_depencency_finder.py
> +def test_scan_and_find_dependencies_golang():
Ack!

2020-09-16 07:28 UTC, dgpatelgit commented
lgtm

2020-09-16 07:31 UTC, dgpatelgit approved these changes
ltgm, but let others also verify their comment before merge.

2020-09-16 11:45 UTC, yzainee requested changes
Minor changes.
Generated file looks fine. Although i have just validated the direct deps. Didnt get a chance to verify each transitive

2020-09-16 11:45 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +        version = version.replace('v', '')
we need to remove the 1st occurrence of v. why are we generically removing all v's? what if the version is like v1.1.1-dev1

2020-09-16 11:45 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
why do we need this?

2020-09-17 06:22 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
its to trigger file directly as a Python Script.

2020-09-17 06:25 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
i do understand that.. we dont need to commit this code. you can have it in your local to test your changes

2020-09-17 06:33 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
even if its in repo.. it will not be any harm.. just a convenience for any developer.

2020-09-17 06:36 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
it wont harm but its not a good thing to have your local test code committed. For testing purpose, you always have the test cases which is anyways picking a sample file and generating a sample output. modify your test case if you want to be more exhaustive

2020-09-17 06:43 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
got more than expected friction for this little chunk.. Removed.

2020-09-17 06:45 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        a['is_semver'] = a['given_version'].count('-') == 0
Ack

2020-09-17 06:45 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        a['version'] = a['given_version'].replace('v', '').split('-')[0].split('+')[0]
Ack

2020-09-17 06:46 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        version = version.replace('v', '')
Ack. Added Test case for Same

2020-09-17 06:46 UTC, yzainee commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
Its not about friction, nobody is a villain here :), its about understanding the point what other is trying to convey.. anyways, good that you removed it.

2020-09-17 06:47 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +if __name__ == '__main__':
Please take a look now.. Let me know what you feel now. Lets close this today.

2020-09-17 09:17 UTC, yzainee approved these changes
LGTM. Please make sure you test the transitive list generated to see if its added correctly. I havnt checked that.

2020-09-17 12:04 UTC, merged