refactoring: SA Maven Utility Functions | Utils Arch changes
fabric8-analytics/fabric8-analytics-utils pull request #69
Opened 2020-10-05 10:29 UTC by deepak1725

Optimization SA Utility Functions

2020-10-09 10:58 UTC, deepak1725 commented
[test]

2020-10-12 09:46 UTC, prashbnair requested changes
I have not reviewed goLang as I do not know the file structure.

2020-10-12 09:46 UTC, prashbnair commented on f8a_utils/tree_generator.py
> +            tree = self._get_tree(data)
rename to get_transitives

2020-10-12 09:46 UTC, prashbnair commented on f8a_utils/tree_generator.py
> +    def _get_transitives(self, transitives: list) -> list:
parse_transitives

2020-10-12 09:46 UTC, prashbnair commented on f8a_utils/tree_generator.py
> +                parsed_json = self._parse_string(direct)
Is the conditon for 'test' missing?

2020-10-12 09:46 UTC, prashbnair commented on f8a_utils/tree_generator.py
> +class NpmDependencyTreeGenerator(DependencyTreeGenerator):
Npm structure also seems similar to maven and the above code can probably be reused.

2020-10-14 04:53 UTC, deepak1725 commented on f8a_utils/tree_generator.py
> +            tree = self._get_tree(data)
it's not really transitives, If you remember we are generating a Parent-Child Relationship tree here and later on iterating over Child (Transitives). 

This method actually generating a Tree here.

2020-10-14 04:56 UTC, deepak1725 commented on f8a_utils/tree_generator.py
> +                parsed_json = self._parse_string(direct)
Do we really need "Test" condition..? Dont really know why it was put in place first time.. 
For me, it looks like Technical Debt.. https://github.com/fabric8-analytics/fabric8-analytics-utils/blob/master/f8a_utils/dependency_finder.py#L51

2020-10-14 06:41 UTC, deepak1725 commented on f8a_utils/tree_generator.py
> +                prefix = prefix.replace('"', '').replace(';', '').strip()
Ack!

2020-10-14 06:41 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        get_dependency_tree = get_tree(ecosystem)()
Ack!

2020-10-14 06:42 UTC, deepak1725 commented on f8a_utils/tree_generator.py
> +    def _get_transitives(self, transitives: list) -> list:
Ack!

2020-10-14 07:01 UTC, prashbnair commented on f8a_utils/tree_generator.py
> +            tree = self._get_tree(data)
Can you then rename to get_dependency_tree?

2020-10-14 07:02 UTC, prashbnair commented on f8a_utils/tree_generator.py
> +                parsed_json = self._parse_string(direct)
Can you please check with @dgpatelgit . He had done some refactoring in this area.

2020-10-14 07:16 UTC, deepak1725 commented on f8a_utils/tree_generator.py
> +            tree = self._get_tree(data)
Okay, Let me try to explain in a pictorial way.
![Blank diagram](https://user-images.githubusercontent.com/21026016/95955952-3cafeb80-0e1b-11eb-9524-69ca467c9ba0.jpeg)

2020-10-14 08:32 UTC, prashbnair requested changes

2020-10-14 08:32 UTC, prashbnair commented on f8a_utils/dependency_finder.py
> +        dependency_tree = get_tree(ecosystem)()
```suggestion
        dependency_tree_generator = get_dependency_tree_generator(ecosystem)()
```

2020-10-14 08:32 UTC, prashbnair commented on f8a_utils/tree_generator.py
> +            tree = self._get_tree(data)
I see that you are calling get_dependencies, there is no get_dependency_tree

2020-10-14 11:20 UTC, deepak1725 commented on f8a_utils/tree_generator.py
> +                parsed_json = self._parse_string(direct)
After Sync up with DGP, Just got to know: `test scope` will be there if tree is generated using 
```
mvn org.apache.maven.plugins:maven-dependency-plugin:3.0.2:tree -DoutputFile=/someloc/dependencies.txt -DoutputType=dot -DappendOutput=true;
``` 
We have to explicitly avoid test modules. Re-Added condition for the same.

2020-10-14 11:28 UTC, deepak1725 commented on f8a_utils/tree_generator.py
> +            tree = self._get_tree(data)
Ack.

2020-10-14 11:29 UTC, deepak1725 commented on f8a_utils/dependency_finder.py
> +        dependency_tree = get_tree(ecosystem)()
ACK.

2020-10-15 09:21 UTC, prashbnair approved these changes

2020-10-16 08:49 UTC, merged