chore : Migrate CI to Github Actions
fabric8-analytics/fabric8-analytics-utils pull request #71
Opened 2020-10-19 10:32 UTC by sawood14012

2020-10-19 10:58 UTC, arajkumar requested changes

2020-10-19 10:58 UTC, arajkumar commented on .github/workflows/CRDA-CI-Build.yml
> +
Please don't add any branding in the file names (like CRDA, Dependency Analytics,..).

I prefer to keep it like CI.yaml or PR.yaml.

2020-10-19 10:58 UTC, arajkumar commented on .github/workflows/CRDA-CI-Build.yml
> +  Linter:
I see that the following lines are repeated for all jobs.,
```
runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
```
Can this be expressed using matrix?

2020-10-19 10:58 UTC, arajkumar commented on qa/actions-run-tests.sh
> +#!/bin/bash
Can this be expressed in GH Actions itself instead of separate script?
https://github.com/codecov/codecov-action

2020-10-19 12:31 UTC, sawood14012 commented on .github/workflows/CRDA-CI-Build.yml
> +
will change it

2020-10-19 12:32 UTC, sawood14012 commented on .github/workflows/CRDA-CI-Build.yml
> +  Linter:
no when we create multiple parallel jobs we cant use matrix although we can use matrix only inside a single job

2020-10-19 12:35 UTC, sawood14012 commented on qa/actions-run-tests.sh
> +#!/bin/bash
i had added it but removed it because it will add two extra checks to the repo

2020-10-19 12:47 UTC, sawood14012 commented on qa/actions-run-tests.sh
> +#!/bin/bash
Done Added

2020-10-19 12:50 UTC, sawood14012 commented on .github/workflows/CRDA-CI-Build.yml
> +  Linter:
i have used matrix now

2020-10-19 13:31 UTC, arajkumar requested changes

2020-10-19 13:31 UTC, arajkumar commented on .github/workflows/ci-build.yml
> +      run:  bash qa/actions-run-tests.sh
As mentioned in the previous comment, I suggest to replace the script with Actions.

```
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
```

2020-10-19 13:31 UTC, arajkumar commented on .github/workflows/ci-build.yml
> +name: CRDA CI Build
Please rename it as CI
```suggestion
name: CI
```

Also rename the file to CI.yaml

2020-10-19 13:31 UTC, arajkumar commented on .github/workflows/ci-build.yml
> +        scripts: ["run-linter", "check-docstyle", "detect-dead-code", "detect-common-errors"]
Use yaml style of array declaration.
```suggestion
        scripts: 
          - run-linter
          - check-docstyle
          - detect-dead-code
          - detect-common-errors
```

2020-10-19 13:31 UTC, arajkumar commented on .github/workflows/ci-build.yml
> +        scripts: ["measure-cyclomatic-complexity","measure-maintainability-index"]
Can you experiment with defining matrix value as object? It will help you eliminate CC-MI and Run-Tests jobs definitions. Something like below.

```
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        checks: 
             - name: Cyclomatic Complexity
                run: bash qa/measure-cyclomatic-complexity.sh --fail-on-error
             - name: Maintainability Index
                run: bash qa/measure-maintainability-index.sh --fail-on-error
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run  ${{ matrix.checks.name }}
      run: ${{ matrix.checks.run }}
```

2020-10-19 13:33 UTC, sawood14012 commented on .github/workflows/ci-build.yml
> +        scripts: ["measure-cyclomatic-complexity","measure-maintainability-index"]
okay

2020-10-19 13:37 UTC, sawood14012 commented on .github/workflows/ci-build.yml
> +      run:  bash qa/actions-run-tests.sh
token is not required for public repos
will change like this

2020-10-19 13:43 UTC, sawood14012 commented on .github/workflows/ci-build.yml
> +        scripts: ["measure-cyclomatic-complexity","measure-maintainability-index"]
negative this cant be done it only allows primitive values

2020-10-20 07:49 UTC, arajkumar reviewed
Overall changes looks good to me with few more nits.

2020-10-20 07:49 UTC, arajkumar commented on qa/measure-cyclomatic-complexity.sh
> +if [ true ]
Remove the complete if branch. Ditto for other file.

2020-10-20 07:49 UTC, arajkumar commented on .github/workflows/ci-build.yml
> +        virtualenv -p python3 venv && source venv/bin/activate
Virtualenv is not necessary

2020-10-20 07:49 UTC, arajkumar commented on .github/workflows/ci-build.yml
> +  Run-Tests:
```suggestion
  Unittests:
```

2020-10-20 07:49 UTC, arajkumar commented on .github/workflows/ci-build.yml
> +  Linter-docstyle:
```suggestion
  Code-Quality-Checks:
```

2020-10-20 07:51 UTC, sawood14012 commented on qa/measure-cyclomatic-complexity.sh
> +if [ true ]
if we remove the if it wont fail even if the complexity is low

2020-10-20 09:09 UTC, arajkumar approved these changes
lgtm

2020-10-20 09:13 UTC, arajkumar commented on qa/measure-cyclomatic-complexity.sh
> +defects="$(radon cc -s -n D -i venv . | wc -l)"
There is a redundant execution of `radan`, which can be resolved in successive PRs. Same for maintainability index as well.

2020-10-20 09:39 UTC, prashbnair approved these changes

2020-10-20 09:55 UTC, merged