chore: Unknown package ingestion utilities.
fabric8-analytics/fabric8-analytics-utils pull request #83
Opened 2020-12-21 13:13 UTC by jparsai

2020-12-21 13:34 UTC, yzainee approved these changes
LGTM

2020-12-21 13:35 UTC, arajkumar commented on f8a_utils/ingestion_utils.py
> +        logger.error(e)
Combine these into single error log.

2020-12-21 13:43 UTC, arajkumar requested changes

2020-12-21 13:43 UTC, arajkumar commented on f8a_utils/ingestion_utils.py
> +    try:
Put exception block to the function which would throw exception, not to all. In this case the potential candidate is _session.post

2020-12-21 13:43 UTC, arajkumar commented on f8a_utils/ingestion_utils.py
> +        elapsed_time = time.time() - started_at
Elapsed time is not required because it is a future based http call.

2020-12-21 13:43 UTC, arajkumar commented on tests/test_ingestion_utils.py
> +def test_ingest_epv(_session):
I would suggest to use exception for flow control, not Bool return value.

For this case, throw exception incase of failure.

2020-12-22 05:46 UTC, arajkumar requested changes

2020-12-22 05:46 UTC, arajkumar commented on f8a_utils/ingestion_utils.py
> +        raise e
Two suggestion,

1. Use try..catch block for the exact function call which would raise exception
2. Don't preformat string which is used in logger

```suggestion
        # Set the unknown packages and versions
        for pkg in unknown_pkgs:
            payload['packages'].append({'package': pkg.name, 'version': pkg.version})

        # If package list is not empty then call ingestion API
        if payload['packages']:
          try:
            _session.post(url=_INGESTION_API_URL,
                json=payload,
                headers={'auth_token': _APP_SECRET_KEY})
          except Exception as e:
            logger.error('Failed to trigger unknown flow for payload %s with error %s'
                , payload, e)
            raise Exception('Ingestion failed') from e
          else:
            logger.info('Ingestion call being executed')
```

2020-12-22 05:50 UTC, jparsai commented on f8a_utils/ingestion_utils.py
> +        raise e
@arajkumar shouldn't we put for loop within try, to throw an error if keys of the set are not given correctly?

2020-12-22 10:46 UTC, dgpatelgit commented on f8a_utils/ingestion_utils.py
> +        "force": False,
Why don't we expose these `force` and `force_graph_sync` two also has parameters? we can use them in future.

2020-12-22 10:51 UTC, jparsai commented on f8a_utils/ingestion_utils.py
> +        "force": False,
The values for these for unknown flow will remain same as we want this to give high priority, it can be done, currently its value will be this only whether we expose it or not.

2020-12-22 11:00 UTC, yzainee commented on f8a_utils/ingestion_utils.py
> +        "force": False,
for unknown flow, we dont need to send these values.

2020-12-22 11:05 UTC, jparsai commented on f8a_utils/ingestion_utils.py
> +        "force": False,
@dgpatelgit as of now we can keep it as it is, because values of force and force_graph_sync are not going to change for unknown flow, if in future we changed something in worker flow we will update and pass it as parameter.

2020-12-24 13:09 UTC, arajkumar requested changes

2020-12-24 13:09 UTC, arajkumar commented on f8a_utils/ingestion_utils.py
> +            payload['packages'].append({'package': pkg.package, 'version': pkg.version})
The caller should follow the calling convention of this function, The function shouldn't adopt the caller. This is an anti pattern.

2020-12-28 07:12 UTC, arajkumar approved these changes
lgtm

2020-12-28 07:13 UTC, merged